UNIVERSE_SIZE = 150
START_DATE    = "2018-01-01"
END_DATE      = "2024-01-01"
FORWARD_DAYS  = 21        # predict 1-month returns
REBAL_FREQ    = 21        # rebalance monthly
TRAIN_WINDOW  = 504       # 2 years training
TEST_WINDOW   = 63        # 3 months testing
COST_BPS      = 10
DATA_DIR      = "data/"
FACTOR_DIR    = "factors/"